// Generated by CoffeeScript 1.8.0
var animalSound, avaiablePets, formatPetDescription, formatPetName, i, nameElement, pet, petOutput, shop;

shop = {
  owner: {
    name: "Ian"
  },
  animals: [
    {
      name: "Kelsey",
      type: "dog",
      breed: "Labrador",
      description: "A sweet and loyal dog. Loves to play fetch. Sometimes drinks out of the toilet."
    }, {
      name: "Sgt. Snuffles",
      type: "dog",
      breed: "Pug",
      description: "Small in stature, but big in heart, Sgt. Snuffles is never one to back down from a mission."
    }, {
      name: "Chomps",
      type: "rabbit",
      breed: "Giant Angora",
      description: "Chomps is usually very good-natured, but he does not take kindly to being mistaken for an ottoman. Come see him in person and you'll understand why that may happen."
    }, {
      name: "Flops",
      type: "rabbit",
      breed: "French Lop",
      description: "Enjoys nothing more than a good roll in the grass and a nap in the sun."
    }, {
      name: "Bopper",
      type: "rabbit",
      breed: "Checkered Giant",
      description: "The quiet one of the group. Loves celery."
    }, {
      name: "Chairman Meow",
      type: "cat",
      breed: "Snowshoe",
      description: "True to his name, Chairman Meow fancies himself in charge."
    }, {
      name: "Jacques",
      type: "cat",
      breed: "Manx",
      description: "A happy-go-lucky cat who occasionally finds himself at odds with Chairman Meow over who gets to sit at the top of the cat tree."
    }, {
      name: "Chupa",
      type: "cat",
      breed: "Scottish Fold",
      description: "Chupa always appears perplexed with the world, but don't be fooled. That's just the way his face is shaped."
    }, {
      name: "Alfred",
      type: "horse",
      breed: "Breton",
      description: "The resident shop patriarch. Very calm and tolerates the antics of the other animals when they sneak into his pen."
    }
  ]
};

formatPetDescription = function(pet) {
  return ("<h2>" + pet.name + "</h2>") + ("<h3 class='breed'>" + pet.breed + "</h3>") + ("<p class='description'>" + pet.description + "</p>");
};

window.selectPet = function(petIndex) {
  var link, pet, petInfo, _i, _len, _ref;
  pet = shop.animals[petIndex];
  petInfo = document.getElementById("pet_information");
  petInfo.innerHTML = formatPetDescription(pet);
  _ref = document.querySelectorAll("#available_pets a");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    link = _ref[_i];
    link.className = "";
  }
  return element.className = "selected";
};

animalSound = function(animal) {
  switch (animal.type) {
    case "cat":
      return "meow";
    case "dog":
      return "bark";
    case "horse":
    case "donkey":
      return "neigh";
    default:
      return "sniff sniff";
  }
};

formatPetName = function(pet) {
  return "" + pet.name + " <span class='sound'>" + (animalSound(pet)) + "!</span>";
};

nameElement = document.getElementById("owner_name");

nameElement.innerHTML = shop.owner.name;

document.title = "" + shop.owner.name + "'s Pet Shop";

petOutput = (function() {
  var _i, _len, _ref, _results;
  _ref = shop.animals;
  _results = [];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    pet = _ref[i];
    _results.push("<li><a href='#' onclick='selectPet(" + i + ", this)'>" + (formatPetName(pet)) + "</a></li>");
  }
  return _results;
})();

avaiablePets = document.getElementById("available_pets");

avaiablePets.innerHTML = petOutput.join("");
