// Generated by CoffeeScript 1.8.0
(function() {
  var avaiablePets, nameElement, pet, petOutput, shop;

  shop = {
    owner: {
      name: "Ronaldo"
    },
    animals: [
      {
        name: "Kelsey",
        type: "dog"
      }, {
        name: "spt. Snuffles",
        type: "dog"
      }, {
        name: "Flops",
        type: "rabbit"
      }, {
        name: "Chomps",
        type: "rabbit"
      }, {
        name: "Boopper",
        type: "rabbit"
      }, {
        name: "Jacques",
        type: "cat"
      }, {
        name: "Chupa",
        type: "cat"
      }, {
        name: "Alfred",
        type: "horse"
      }
    ]
  };

  nameElement = document.getElementById("owner_name");

  nameElement.innerHTML = shop.owner.name;

  document.title = "" + shop.owner.name + "'s Pet Shop";

  petOutput = (function() {
    var _i, _len, _ref, _results;
    _ref = shop.animals;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pet = _ref[_i];
      _results.push("<li>" + (pet.name.toUpperCase()) + "</li>");
    }
    return _results;
  })();

  avaiablePets = document.getElementById("available_pets");

  avaiablePets.innerHTML = petOutput.join("");

}).call(this);
